version: "3" #Задаем версию docker-compose.yml
services:
  first:
    build: .
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  second:
    build: ./Part_6
    ports:
      - 80:8080
    depends_on:
      - first